# Modified by acs (fork of CidVonHighwind/microreader), 2026-10-07: fork versioning from acs-v* git tags.
import os
import subprocess

# Fork versioning: the version comes from git tags named "acs-v<version>" (e.g. acs-v1.3).
#   - build exactly on the tag      -> "1.3 by acs"
#   - N commits after the tag       -> "1.3+N by acs"   (development build)
#   - no acs-v* tag yet             -> "dev by acs"
# A version.txt in the repo root (git-ignored) overrides everything, for one-off local builds.
TAG_PREFIX = "acs-v"
SUFFIX = " by acs"


def _git(*args):
    return subprocess.check_output(["git", *args], stderr=subprocess.DEVNULL).strip().decode("utf-8")


def get_fork_version():
    try:
        tag = _git("describe", "--tags", "--abbrev=0", "--match", f"{TAG_PREFIX}*")
    except Exception:
        return f"dev{SUFFIX}"
    version = tag[len(TAG_PREFIX):]
    try:
        ahead = int(_git("rev-list", "--count", f"{tag}..HEAD"))
    except Exception:
        ahead = 0
    return f"{version}{'+' + str(ahead) if ahead else ''}{SUFFIX}"


def get_git_hash():
    try:
        hash_str = _git("rev-parse", "--short", "HEAD")
        dirty = _git("status", "--porcelain")
        return f"{hash_str}{'-dirty' if dirty else ''}"
    except Exception:
        return "unknown"


def generate():
    try:
        Import("env")  # SCons / PlatformIO hook
        root_dir = env.get("PROJECT_DIR")
    except NameError:
        root_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    version_file = os.path.join(root_dir, "version.txt")
    header_file = os.path.join(root_dir, "lib", "microreader", "version.h")

    if os.path.exists(version_file):
        with open(version_file, "r", encoding="utf-8") as f:
            full_version = f.read().strip()
    else:
        full_version = get_fork_version()

    git_hash = get_git_hash()

    header_content = f"""// Auto-generated by tools/generate_version.py
#pragma once

#define MICROREADER_VERSION "{full_version}"
#define MICROREADER_GIT_HASH "{git_hash}"
"""

    # Write only if changed to avoid unnecessary recompilations
    current_content = ""
    if os.path.exists(header_file):
        with open(header_file, "r", encoding="utf-8") as f:
            current_content = f.read()

    if current_content != header_content:
        with open(header_file, "w", encoding="utf-8") as f:
            f.write(header_content)
        print(f"Generated version.h: {full_version}")


generate()
